name: Benchmark

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Normalization benchmark
        run: composer benchmark -- --group=normalization

      - name: Denormalization benchmark
        run: composer benchmark -- --group=denormalization